export const Allproducts=[
    {
      id: 0,
      qty: 1,
      category: `cat`,
      name: `9Lives Cat Plus Care Dry Food 12oz #13291, 12 Ounce (Pack of 1), Multicolored`,
      price: 5.62,
      img: `https://m.media-amazon.com/images/I/61V1nxFDuEL._AC_SL1421_.jpg`,
      
    },
    {
      id: 1,
      qty: 1,
      category: `cat`,
      name: `Healthier Paws Fancy Feast Creamy Delights Chicken Feast with a Touch of Real Milk in A Creamy Sauce, 3 oz. Can (Pack of 12) Sticker!!`,
      price: 29.80,
      img: `https://m.media-amazon.com/images/I/610V3XyUbXL._AC_SX679_.jpg`,
      
    },
    {
      id: 2,
      qty: 1,
      category: `dog`,
      name: `Royal Canin Adult Shih Tzu Wet Dog Food, 3 oz Pouch (Pack of 12)`,
      price: 44.99,
      img: `https://m.media-amazon.com/images/I/817tAZEIBXL._AC_SX679_.jpg`,
      
    },
    {
      id: 3,
      qty: 1,
      category: `dog`,
      name: `Kinpur Pet Care Natural Calming Chews for Dogs with Hemp Oil and Valerian Root (Chicken, 180 Chews)`,
      price: 20.66,
      img: `https://m.media-amazon.com/images/I/81wHhHhfK2L._AC_SX679_.jpg`,
      
    },
    {
      id: 4,
      qty: 1,
      category: `dog`,
      name: `Blue Buffalo Wilderness High Protein Dry Dog Food, Chicken Recipe`,
      price: 59.98,
      img: `https://m.media-amazon.com/images/I/71PKE1Iy5-L._SX522_.jpg`,
      
    },
    {
      id: 5,
      qty: 1,
      category: `cat`,
      name: `Purina ONE Natural Dry Cat Food, Tender Selects Blend With Real Chicken`,
      price: 24.68,
      img: `https://m.media-amazon.com/images/I/71M+j-NMAnL._AC_SX679_.jpg`,
    },
    {
      id: 6,
      qty: 1,
      category: `cat`,
      name: `IAMS Proactive Health Indoor Weight and Hairball Care Dry Cat Food`,
      price: 23.84,
      img: `https://m.media-amazon.com/images/I/71KD4VIyGmL._AC_SX679_.jpg`,
    },
    {
      id: 7,
      qty: 1,
      category: `dog`,
      name: `Rachael Ray Nutrish Real Beef and Brown Rice Recipe Dry Dog Food`,
      price: 39.98,
      img: `https://m.media-amazon.com/images/I/81O3kJkAICL._AC_SX679_.jpg`,
    },
      {
        id: 8,
        qty: 1,
        category: `dog`,
        name: `Purina Pro Plan Sensitive Skin and Stomach Dry Dog Food, Salmon and Rice Formula`,
        price: 52.98,
        img: `https://m.media-amazon.com/images/I/81em+N9m9NL._AC_SX679_.jpg`,
      },
      {
        id: 9,
        qty: 1,
        category: `cat`,
        name: `Hill's Science Diet Dry Cat Food, Adult, Indoor`,
        price: 40.99,
        img: `https://m.media-amazon.com/images/I/71iU-35uwzL._SL1500_.jpg`,
      },
      {
        id: 10,
        qty: 1,
        category: `cat`,
        name: `Wellness CORE Natural Grain Free Dry Cat Food`,
        price: 22.39,
        img: `https://m.media-amazon.com/images/I/81nlBr4jPbL._AC_SL1500_.jpg`,
      },
      {
        id: 11,
        qty: 1,
        category: `dog`,
        name: `Merrick Backcountry Grain Free Dry Dog Food, Pacific Catch Recipe`,
        price: 59.99,
        img: `https://m.media-amazon.com/images/I/8176h0uf8wL._AC_SX679_.jpg`,
      },
      {
        id: 12,
        qty: 1,
        category: `dog`,
        name: `CANIDAE PURE Real Salmon, Limited Ingredient, Grain Free Premium Dry Dog Food`,
        price: 64.99,
        img: `https://cdn11.bigcommerce.com/s-lnkn0tcvqc/images/stencil/1280x1280/products/881/1320/2023_Pure_GF_Salmon_front-largebag__00109.1681161047.png?c=1`,
      },
      {
        id: 13,
        qty: 1,
        category: `cat`,
        name: `Blue Buffalo Wilderness High Protein Grain Free, Natural Adult Dry Cat Food`,
        price: 36.98,
        img: `https://m.media-amazon.com/images/I/51Hk7tgoQuL._SX300_SY300_QL70_FMwebp_.jpg`,
      },
      {
        id: 14,
        qty: 1,
        category: `cat`,
        name: `Purina Fancy Feast Gravy Wet Cat Food Variety Pack, Poultry & Beef Grilled Collection`,
        price: 17.98,
        img: `https://m.media-amazon.com/images/I/81JxOnaw0pL._AC_SX522_.jpg`,
      },
      {
        id: 15,
        qty: 1,
        category: `dog`,
        name: `Taste of the Wild Grain Free High Protein Real Meat Recipe Premium Dry Dog Food`,
        price: 48.99,
        img: `https://m.media-amazon.com/images/I/81iMAh6DLnL._AC_SL1500_.jpg`,
      },
      
  
  ]